# Generated by Django 5.2.4 on 2025-07-02 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMPARecyclingEndosome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_count', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Astrocyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitored_activity', models.FloatField(default=0.0)),
                ('tnf_alpha', models.FloatField(default=0.0)),
                ('d_serine', models.FloatField(default=0.0)),
                ('atp', models.FloatField(default=0.0)),
                ('release_rate', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationProteinPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(default=100)),
                ('last_refilled', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DopamineCleft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dopamine', models.FloatField(default=0.0)),
                ('clear_rate', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='DopamineReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bound', models.BooleanField(default=False)),
                ('kd', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='ModulatoryCascade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.FloatField(default=0.0)),
                ('pka_activity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NMDAReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mg_blocked', models.BooleanField(default=True)),
                ('glutamate_thr', models.FloatField(default=1.0)),
                ('voltage_thr', models.FloatField(default=-50.0)),
            ],
        ),
        migrations.CreateModel(
            name='PostSynapticDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ampa_count', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostSynapticMembrane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_potential', models.FloatField(default=-70.0)),
                ('potential', models.FloatField(default=-70.0)),
                ('depolarization', models.FloatField(default=20.0)),
            ],
        ),
        migrations.CreateModel(
            name='SpineHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_concentration', models.FloatField(default=0.0)),
                ('ca_sensitivity', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='STDPParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltp_threshold', models.FloatField(default=5.0)),
                ('ltd_threshold', models.FloatField(default=1.0)),
                ('ltp_rate', models.FloatField(default=0.01)),
                ('ltd_rate', models.FloatField(default=0.005)),
            ],
        ),
        migrations.CreateModel(
            name='SynapticCleft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glutamate', models.FloatField(default=0.0)),
                ('clear_rate', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='SynapticTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged', models.BooleanField(default=False)),
                ('time_tagged', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraffickingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertion_rate', models.FloatField(default=5.0)),
                ('removal_rate', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='Synapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('astrocyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.astrocyte')),
                ('cascade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.modulatorycascade')),
                ('da_cleft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.dopaminecleft')),
                ('da_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.dopaminereceptor')),
                ('endosome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='synapse.amparecyclingendosome')),
                ('membrane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.postsynapticmembrane')),
                ('nmda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.nmdareceptor')),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='synapse.consolidationproteinpool')),
                ('psd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='synapse.postsynapticdensity')),
                ('spine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='synapse.spinehead')),
                ('stdp_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.stdpparameters')),
                ('cleft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.synapticcleft')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='synapse.synaptictag')),
                ('traf_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.traffickingparameters')),
            ],
        ),
    ]
