# Generated by Django 5.2.4 on 2025-07-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synapse',
            name='history_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='synapse',
            name='last_plasticity_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synapticcleft',
            name='last_spike_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synapticcleft',
            name='spike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synapticcleft',
            name='spike_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
